### ISSUE TITLE
Limit in 64 characters is too short

### ISSUE THREAD

**Issue by greybax** [Azure/azure-mobile-engagement-app-ios#6]
I'm using `sendActivity`, `sendSessionEvent`, `sendEvent` and other with first parameter which means name of some action in format as:

    `${rootViewPath}.${someActionName}`

In some cases this generated too long string which do not pass validation of 64 characters.

P.S I've created similar issue here https://github.com/Azure/azure-mobile-engagement-cordova/issues/51 but I think that this is issue can be fixed in native SDK

**Comment by iamclement** [comment]
Mobile Engagement service is retired
